In [1]:
import numpy as np

# 1 Question

In [5]:
arr=np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(arr)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


# 2 Question

In [6]:
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


# 3 Question

In [7]:
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 5 Question

In [15]:
x= np.random.random((3,3))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.31410806 0.3500257  0.74720744]
 [0.87599761 0.74771267 0.29247127]
 [0.18060406 0.81508347 0.37326154]]
After normalization:
[[0.19198338 0.24363419 0.81479528]
 [1.         0.81552181 0.16086892]
 [0.         0.91240335 0.27704812]]


# 6 Question

In [16]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


# 7 Question

In [17]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)


Yestraday:  2020-07-26
Today:  2020-07-27
Tomorrow:  2020-07-28


# 8 Question

In [18]:
import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)

Original array:
[0.75004802 0.69544081 0.05568665 0.26821097 0.30514451 0.3001627
 0.36032602 0.1988823  0.8240036  0.00821146]
Maximum value replaced by 0:
[0.75004802 0.69544081 0.05568665 0.26821097 0.30514451 0.3001627
 0.36032602 0.1988823  0.         0.00821146]


# 10 Question

In [26]:
x = np.ones((4, 4))
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# 11 Question

In [27]:
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.78159805 0.83445497 0.56313372 0.05661887 0.24010426 0.26101771
  0.01196757 0.96082626 0.74163933 0.30052119]
 [0.9995218  0.54937396 0.32877094 0.50662712 0.75703304 0.92201333
  0.1665723  0.95030378 0.16571832 0.92954255]
 [0.54583885 0.35874402 0.58868941 0.77694487 0.15006992 0.37302669
  0.3964866  0.73975112 0.0191519  0.52706269]
 [0.45698191 0.05350557 0.37287765 0.24933289 0.65667983 0.09629642
  0.46683604 0.41588297 0.71969204 0.50438719]
 [0.01570326 0.97187501 0.85806828 0.83389864 0.42733695 0.89675306
  0.51998863 0.28871992 0.04926848 0.766149  ]]

Subtract the mean of each row of the said matrix:

[[ 0.30640986  0.35926678  0.08794552 -0.41856932 -0.23508393 -0.21417049
  -0.46322062  0.48563807  0.26645113 -0.174667  ]
 [ 0.37197409 -0.07817375 -0.29877678 -0.1209206   0.12948533  0.29446561
  -0.46097541  0.32275606 -0.46182939  0.30199483]
 [ 0.09826225 -0.08883259  0.14111281  0.32936826 -0.29750669 -0.07454992
  -0.05109     0.29217451 -0.4

# 12 Question

In [28]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)


[4. 4. 3. 3. 6. 2. 2. 2. 3. 1.]


# 13 Question

In [33]:
A = np.random.randint(0,10,(3,3))
B= np.random.randint(0,10,(3,3))
#Slow version

np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([63, 48, 62])

In [34]:
Z = np.random.randint(0,10,40)
print (Z)
print('rank:', np.bincount(Z).argmax())

[6 0 9 5 1 4 8 4 5 6 9 5 9 4 4 7 0 0 2 2 9 4 2 8 9 4 8 5 4 4 9 8 9 7 8 4 8
 7 9 8]
rank: 4


# 14 Question

In [38]:
Z = np.arange(1000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[995 996 997 998 999]
[995 998 999 997 996]
